file_hello = open("D:\\AutomateTheBoringStuff\\files_hello1.txt", "w")
file_hello.write("This is s a string\n")
file_hello.write("This is s a string1\n")
file_hello.write("This is s a string2\n")
file_hello.write("This is s a string3\n")
file_hello.close()
